name: 🚀 Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🛠 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📤 Deploy to Render via API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering redeploy on Render..."
          curl -X POST https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}             -H "Authorization: Bearer ${RENDER_API_KEY}"             -H "Accept: application/json"             -H "Content-Type: application/json"