version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - model_cache:/app/models
    depends_on:
      - redis
      - clamav

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  clamav:
    image: clamav/clamav:latest
    volumes:
      - clamav_data:/var/lib/clamav

volumes:
  redis_data:
  clamav_data:
  model_cache: