services:
  - type: web
    name: scamshot-app
    env: docker
    buildCommand: ""
    startCommand: streamlit run app/dashboard/main.py
    autoDeploy: true

  - type: background
    name: scamshot-retrain
    env: docker
    startCommand: python cron/retrain_model.py
    schedule: "0 2 * * *"

  - type: web
    name: scamshot-api
    env: docker
    plan: free
    startCommand: python -m flask run --host=0.0.0.0 --port=5000
    buildCommand: ""
